### PR TITLE
fix(cargo-tangle): CLI bugs

### LINKED ISSUE #404: [BUG] Panic when trying to run the gadget using gadget-cli
Trying to run the hello world blueprint's gadget after building result in the following error:

```
thread 'main' panicked at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gadget-sdk-0.2.3/src/config.rs:135:18:
called `Result::unwrap()` on an `Err` value: InvalidStringLength
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Command Used to run the gadget

```bash
./target/debug/hello-blueprint run --bind-addr 127.0.0.1 --bind-port 6754 --blueprint-id 0 --service-id 0 --chain local_testnet --http-rpc-url http://127.0.0.1:9944 --keystore-uri file://target/keystore --pretty --protocol tangle --ws-rpc-url ws://127.0.0.1:9944
```

Full backtrace:
```rust
thread 'main' panicked at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gadget-sdk-0.2.3/src/config.rs:135:18:
called `Result::unwrap()` on an `Err` value: InvalidStringLength
stack backtrace:
   0:     0x5651944f69fa - std::backtrace_rs::backtrace::libunwind::trace::had463f8f1f0b6399
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x5651944f69fa - std::backtrace_rs::backtrace::trace_unsynchronized::h4d82d1716c5b0264
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5651944f69fa - std::sys::backtrace::_print_fmt::h65b38b72358829cc
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/sys/backtrace.rs:66:9
   3:     0x5651944f69fa - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h8b2043b14ab05304
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/sys/backtrace.rs:39:26
   4:     0x56519451f8f3 - core::fmt::rt::Argument::fmt::h4665a6919989af23
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/core/src/fmt/rt.rs:177:76
   5:     0x56519451f8f3 - core::fmt::write::hf9887d457cdbc966
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/core/src/fmt/mod.rs:1186:21
   6:     0x5651944f2573 - std::io::Write::write_fmt::ha659b10ba83556c4
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/io/mod.rs:1839:15
   7:     0x5651944f6842 - std::sys::backtrace::BacktraceLock::print::hf85affc2cf4419f7
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/sys/backtrace.rs:42:9
   8:     0x5651944f792c - std::panicking::default_hook::{{closure}}::hde5089a7c4039350
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/panicking.rs:268:22
   9:     0x5651944f7772 - std::panicking::default_hook::hf6b38aee6b14f9c5
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/panicking.rs:295:9
  10:     0x5651944f7f67 - std::panicking::rust_panic_with_hook::hafbd7f0e47ba5b9a
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/panicking.rs:801:13
  11:     0x5651944f7dfa - std::panicking::begin_panic_handler::{{closure}}::heb41764772c3697f
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/panicking.rs:674:13
  12:     0x5651944f6ed9 - std::sys::backtrace::__rust_end_short_backtrace::hcc198f67593013e0
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/sys/backtrace.rs:170:18
  13:     0x5651944f7a8c - rust_begin_unwind
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/panicking.rs:665:5
  14:     0x56519451d230 - core::panicking::panic_fmt::hd2428fc03641ffed
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/core/src/panicking.rs:74:14
  15:     0x56519451d716 - core::result::unwrap_failed::hd8cd9da81f943b48
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/core/src/result.rs:1700:5
  16:     0x56519397b926 - core::result::Result<T,E>::unwrap::hbd196110cea1261f
                               at /nix/store/1ixjn5mk15pzqfcpj4rfvv7p6xnf1y2d-rust-minimal-1.83.0-nightly-2024-10-13/lib/rustlib/src/rust/library/core/src/result.rs:1104:23
  17:     0x56519397b926 - <gadget_sdk::config::EigenlayerContractAddresses as core::default::Default>::default::hfd2dd421ead3ebe5
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gadget-sdk-0.2.3/src/config.rs:132:40
  18:     0x56519397d315 - gadget_sdk::config::load_inner::h2b88328e767ee87f
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gadget-sdk-0.2.3/src/config.rs:405:36
  19:     0x56519397be9e - gadget_sdk::config::load_with_lock::h319561da837a7541
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gadget-sdk-0.2.3/src/config.rs:354:5
  20:     0x56519397be7e - gadget_sdk::config::load::hbec7f9e8b55915b0
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gadget-sdk-0.2.3/src/config.rs:339:5
  21:     0x565193748ee0 - frost_gadget::main::{{closure}}::ha43b1ab86b90b181
                               at /home/shady/github/webb-tools/frost-blueprint/src/main.rs:9:1
  22:     0x5651936ec4fb - <core::pin::Pin<P> as core::future::future::Future>::poll::hc41d171e0d6bf06c
                               at /nix/store/1ixjn5mk15pzqfcpj4rfvv7p6xnf1y2d-rust-minimal-1.83.0-nightly-2024-10-13/lib/rustlib/src/rust/library/core/src/future/future.rs:123:9
  23:     0x5651936fe04e - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::h00d3ec8a8b1db793
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/park.rs:281:63
  24:     0x5651936fd136 - tokio::runtime::coop::with_budget::h6ea385ce4045e87c
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:107:5
  25:     0x5651936fd136 - tokio::runtime::coop::budget::hcf75c50ac0b2824c
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:73:5
  26:     0x5651936fd136 - tokio::runtime::park::CachedParkThread::block_on::h086b9d682d2a414f
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/park.rs:281:31
  27:     0x56519370521f - tokio::runtime::context::blocking::BlockingRegionGuard::block_on::h20a517ab0337bdba
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/blocking.rs:66:9
  28:     0x565193795bf0 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}::hbad092e85de6825a
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  29:     0x5651937aca53 - tokio::runtime::context::runtime::enter_runtime::h43e0ea8eb660a40f
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/runtime.rs:65:16
  30:     0x565193795b41 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h7faeb0e70e2e41fb
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  31:     0x565193751ea8 - tokio::runtime::runtime::Runtime::block_on_inner::ha120924776acaccd
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:363:45
  32:     0x565193752321 - tokio::runtime::runtime::Runtime::block_on::h1e367275a0078e05
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:333:13
  33:     0x56519379ac41 - frost_gadget::main::h8297a5cdee182d63
                               at /home/shady/github/webb-tools/frost-blueprint/src/main.rs:9:1
  34:     0x56519370769b - core::ops::function::FnOnce::call_once::hbb64d51a9dff73e1
                               at /nix/store/1ixjn5mk15pzqfcpj4rfvv7p6xnf1y2d-rust-minimal-1.83.0-nightly-2024-10-13/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  35:     0x5651936ef17e - std::sys::backtrace::__rust_begin_short_backtrace::h80da47ed9b795d04
                               at /nix/store/1ixjn5mk15pzqfcpj4rfvv7p6xnf1y2d-rust-minimal-1.83.0-nightly-2024-10-13/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:154:18
  36:     0x56519373b351 - std::rt::lang_start::{{closure}}::h3ff80ea34173debc
                               at /nix/store/1ixjn5mk15pzqfcpj4rfvv7p6xnf1y2d-rust-minimal-1.83.0-nightly-2024-10-13/lib/rustlib/src/rust/library/std/src/rt.rs:195:18
  37:     0x5651944eaf3e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6b45968bb03cc02b
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/core/src/ops/function.rs:284:13
  38:     0x5651944eaf3e - std::panicking::try::do_call::hd54f0ee6864afbc2
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/panicking.rs:557:40
  39:     0x5651944eaf3e - std::panicking::try::h8fe1e0ae419f374f
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/panicking.rs:520:19
  40:     0x5651944eaf3e - std::panic::catch_unwind::h3ab84fbd4591ab9b
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/panic.rs:358:14
  41:     0x5651944eaf3e - std::rt::lang_start_internal::{{closure}}::h5ed0d8319bf3d939
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/rt.rs:174:48
  42:     0x5651944eaf3e - std::panicking::try::do_call::h75e456b0b947b949
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/panicking.rs:557:40
  43:     0x5651944eaf3e - std::panicking::try::hbe8616eebdd8878b
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/panicking.rs:520:19
  44:     0x5651944eaf3e - std::panic::catch_unwind::h385e8be56a3d1a7b
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/panic.rs:358:14
  45:     0x5651944eaf3e - std::rt::lang_start_internal::h6f92389acb32f739
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/rt.rs:174:20
  46:     0x56519373b32a - std::rt::lang_start::h193bd9e7bbadd0ab
                               at /nix/store/1ixjn5mk15pzqfcpj4rfvv7p6xnf1y2d-rust-minimal-1.83.0-nightly-2024-10-13/lib/rustlib/src/rust/library/std/src/rt.rs:194:17
  47:     0x56519379ad0e - main
  48:     0x7f49a908b27e - __libc_start_call_main
  49:     0x7f49a908b339 - __libc_start_main_alias_2
  50:     0x5651936a1aa5 - _start
  51:                0x0 - <unknown>
```

Following the backtrace, looks like the issue is when loading the following configuration:
https://github.com/tangle-network/gadget/blob/27e774cd27f1f66d65279c1b5b854cbad178ddd3/sdk/src/config.rs#L116-L117
Which is poorly written here: https://github.com/tangle-network/gadget/blob/27e774cd27f1f66d65279c1b5b854cbad178ddd3/sdk/src/config.rs#L121-L150 no errors are handled and instead it panics with even no clear error message.

fyi; The error originally raised from here: https://github.com/tangle-network/gadget/blob/27e774cd27f1f66d65279c1b5b854cbad178ddd3/sdk/src/config.rs#L405

### LINKED ISSUE #405: [TASK] Remove structopt and just use clap v4
https://docs.rs/structopt/latest/structopt/#maintenance

As clap v3 is now out, and the structopt features are integrated into (almost as-is), structopt is now in maintenance mode: no new feature will be added.

### PR DESCRIPTION
**Pull request by shekohex**
This pull request includes a series of changes primarily focused on replacing `structopt` with `clap` for command-line argument parsing across multiple files and projects. Additionally, there are some minor refactors and updates to dependencies and configurations.

**Migration from `structopt` to `clap`:**

* [`blueprint-manager/src/config.rs`](diffhunk://#diff-c23486c3b14b30ae524c0c7d1c94bc5c96d50ec83becd39c3c4020d199851341R1-R29): Replaced `structopt` with `clap` for parsing command-line arguments in `BlueprintManagerConfig`. Updated attribute macros accordingly.
* [`blueprint-manager/src/main.rs`](diffhunk://#diff-5af4b69b114fb86eec2f4094f227a6b0d7238f77da8c3592c33174631e99ce3eR5-R13): Updated the usage of `BlueprintManagerConfig` to use `clap`'s `parse` method instead of `structopt`'s `from_args`.
* [`blueprints/incredible-squaring-eigenlayer/src/runner.rs`](diffhunk://#diff-8f57961a8d33999cc38fa347b581167113881210194efb55c0d6c5f2052fbe51R25-L28): Replaced `structopt` with `clap` for parsing command-line arguments in `ContextConfig`. [[1]](diffhunk://#diff-8f57961a8d33999cc38fa347b581167113881210194efb55c0d6c5f2052fbe51R25-L28) [[2]](diffhunk://#diff-8f57961a8d33999cc38fa347b581167113881210194efb55c0d6c5f2052fbe51L214-R214)
* [`gadget-io/src/imp/standard/shell.rs`](diffhunk://#diff-b386c1615394520a00f0dfb8215c53372682242e257a6065fe379e0927d278fbR2-R59): Replaced `structopt` with `clap` for parsing command-line arguments in `Opt` and `GadgetConfig`.
* [`gadget-io/src/shared/shell.rs`](diffhunk://#diff-3b5d5ad31aceb3d2eb1ed64563ff45d8571a0da81b9d54d3dc53e0c68f615dd8L10-R11): Updated `SupportedChains` enum to use `clap::ValueEnum` instead of `structopt`.

**Dependency and Configuration Updates:**

* `Cargo.toml` files across multiple projects: Removed `structopt` and added `clap` with relevant features. [[1]](diffhunk://#diff-dd70089194a21e881d628a3f5773cb2737b6b313d83c831df04ac88d836f71f8R15-L17) [[2]](diffhunk://#diff-a9003d798fd576dcd81adad642ac47d59d82f9e1548e3467861c0531066c65d2L45-R45) [[3]](diffhunk://#diff-6eff0bd9ae51c620ed2a0d2b6569a6e3d41dd54a3cbb7f8718a590766632fcf1L29) [[4]](diffhunk://#diff-7d2239a32c249c622caf0518365ad3f62e73983e31a934ca6d86ce0ca99a0b75L24) [[5]](diffhunk://#diff-6345f01ded14bd88858d7b10f285430696e3b9c794e2d343898221ddcec37431R11) [[6]](diffhunk://#diff-6345f01ded14bd88858d7b10f285430696e3b9c794e2d343898221ddcec37431L21) [[7]](diffhunk://#diff-6345f01ded14bd88858d7b10f285430696e3b9c794e2d343898221ddcec37431R40-L42)
* [`cli/src/main.rs`](diffhunk://#diff-37970e7d817d4316a093bb967d74ff7e26d9c6c01d93f5a79d3d195ba9f6155bL130-R143): Added environment variable support and improved error messages for key generation. [[1]](diffhunk://#diff-37970e7d817d4316a093bb967d74ff7e26d9c6c01d93f5a79d3d195ba9f6155bL130-R143) [[2]](diffhunk://#diff-37970e7d817d4316a093bb967d74ff7e26d9c6c01d93f5a79d3d195ba9f6155bR164-R174)

**Minor Refactors and Documentation:**

* [`blueprint-manager/src/sdk/entry.rs`](diffhunk://#diff-a655fa912403feef1b7c05c9d3c4481defa04004a495e09628e6980fa1cf1de1L24-R24): Changed the type of `verbose` from `i32` to `u8` to match the changes in command-line argument parsing.
* [`blueprint-test-utils/src/lib.rs`](diffhunk://#diff-c499bdcd78ea59396d854b3024b664efda437404e4fdb64c79a74910e400465aL49-R49): Changed the type of `verbose` from `i32` to `u8` in `PerTestNodeInput`.
* [`macros/blueprint-proc-macro/src/lib.rs`](diffhunk://#diff-0642fb7c044af581c1c3633d6b2f74db63527cd62000a73071feb1d9e092b794R125-R137): Added documentation for the `main` procedural macro.

These changes streamline the command-line argument parsing process and ensure consistency across the codebase by using `clap` instead of `structopt`.

Closes #404
Closes #405

### CODE REVIEW

File: sdk/src/config.rs [hunk 1]
```diff
@@ -261,72 +251,95 @@ pub enum Error {
...
+            env = "OPERATOR_STATE_RETRIEVER_ADDR",
+            required_if_eq("protocol", Protocol::Eigenlayer.as_str())
+        )]
+        operator_state_retriever: Option<Address>,
+        /// The address of the delegation manager
+        #[arg(
+            long,
+            value_name = "ADDR",
+            env = "DELEGATION_MANAGER_ADDR",
+            required_if_eq("protocol", Protocol::Eigenlayer.as_str())
```
Comment (drewstone) [inline sdk/src/config.rs:332]: cool!

**Review by drewstone — APPROVED** [review]
Looks great!

**Review by Serial-ATA — APPROVED** [review]
